# Configuración Mosquitto — Prototipo Servientrega
# Permite conexiones anónimas para desarrollo local

listener 1883
allow_anonymous true

# Puerto WebSocket (útil si quieres conectar el front directo al MQTT)
listener 9001
protocol websockets
allow_anonymous true

# Persistencia
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_type error
log_type warning
log_type notice
